# Generated by Django 4.2.7 on 2023-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
            ],
        ),
    ]
